### ISSUE TITLE
Valid for timeseries?

### ISSUE THREAD

**Issue by roesgaard** [radix-ai/conformal-tights#13]
Hi, interesting work!
I will keep an eye on this project for sure!

Quick question: Will this be valid for timeseries? I am specifically thinking about whether you have considered if the splitting should be shuffled=false?

(Also the classification addition from another post sounds interesting!)

**Comment by lsorber** [comment]
> Hi, interesting work!
> I will keep an eye on this project for sure!

Hi, thank you!

> Quick question: Will this be valid for timeseries? I am specifically thinking about whether you have considered if the splitting should be shuffled=false?

Yes, it should be valid for time series (both regression, and in the future classification) under certain assumptions such as stationarity of the underlying process. Do note that the training data must be time-lagged *before* passing it to the estimator (as opposed to having the wrapped estimator do the time-lagging).

I'll leave this issue open as a reminder to demonstrate support for time series in the README, and potentially add functionality if we're missing any.

> (Also the classification addition from another post sounds interesting!)

A preview of what we think conformal prediction for classification could look like can be seen in [Neo LS-SVM](https://github.com/lsorber/neo-ls-svm), which is a modern Least-Squares Support Vector Machine implementation with conformal prediction built in for both regression and classification. Feedback welcome!

**Comment by lsorber** [comment]
Update: we're working on adding support for time series forecasting with [Darts](https://github.com/unit8co/darts).

**Comment by lsorber** [comment]
Conformally calibrated time series forecasting support added in v0.3.0 🎉! See the README for example usage: https://github.com/radix-ai/conformal-tights?tab=readme-ov-file#forecasting-time-series
