### ISSUE TITLE
Question on Pre-fitted models

### ISSUE THREAD

**Issue by phoitack** [radix-ai/conformal-tights#31]
Hi there,

     Not an issue but a question. I noticed that in version 0.4, there is a statement saying the conformal quantile regression will accept pre-fitted regressors. Do I have to specify anything special in the arguments when calling the ConformalCoherentQuantileRegressor object? Thanks.

~ Charlie Lew

**Comment by lsorber** [comment]
Hi Charlie, no you don't need to do anything special, just pass in your fitted estimator `my_estimator` as `ConformalCoherentQuantileRegressor(my_estimator)` and you should be good to go!

Conformal Tights will check if the estimator is already fitted and if so use it as-is, else it will fit it for you using all available input data.

**Comment by phoitack** [comment]
Awesome. Thank you for the explanation.
